import { useLocale } from "@/hooks/useLocale";

const copy = {
  portal: ["بوابة المؤسسات", "Organizations Portal"],
  administration: ["إدارة المنصة", "Platform Administration"],
  dashboard: ["لوحة التحكم", "Dashboard"],
  organizations: ["المؤسسات", "Organizations"],
  subscriptions: ["الاشتراكات", "Subscriptions"],
  signOut: ["تسجيل الخروج", "Sign out"],
  light: ["فاتح", "Light"],
  dark: ["داكن", "Dark"],
  welcomeBack: ["مرحبًا بعودتك", "Welcome back"],
  loginTitle: ["تسجيل دخول إدارة المنصة", "Platform admin sign in"],
  loginSubtitle: [
    "أدخل بيانات حسابك للوصول إلى مركز إدارة المؤسسات",
    "Enter your credentials to access the organization command center",
  ],
  email: ["البريد الإلكتروني", "Email address"],
  password: ["كلمة المرور", "Password"],
  signingIn: ["جارٍ تسجيل الدخول...", "Signing in..."],
  signIn: ["تسجيل الدخول", "Sign in"],
  secureAccess: ["وصول آمن ومشفّر", "Secure encrypted access"],
  dashboardSubtitle: [
    "رؤية شاملة لأداء المؤسسات والاشتراكات",
    "A complete view of organizations and subscriptions",
  ],
  totalOrganizations: ["إجمالي المؤسسات", "Total organizations"],
  activeSubscriptions: ["الاشتراكات النشطة", "Active subscriptions"],
  expiredSubscriptions: ["الاشتراكات المنتهية", "Expired subscriptions"],
  totalRevenue: ["إجمالي الإيرادات", "Total revenue"],
  organizationsSubtitle: [
    "إدارة المؤسسات والحسابات المرتبطة بها",
    "Manage organizations and their administrator accounts",
  ],
  addOrganization: ["إضافة مؤسسة", "Add organization"],
  editOrganization: ["تعديل المؤسسة", "Edit organization"],
  searchOrganizations: [
    "ابحث بالاسم أو البريد الإلكتروني",
    "Search by name or email",
  ],
  search: ["بحث", "Search"],
  name: ["الاسم", "Name"],
  nameAr: ["اسم المؤسسة بالعربية", "Arabic organization name"],
  nameEn: ["اسم المؤسسة بالإنجليزية", "English organization name"],
  type: ["النوع", "Type"],
  organizationType: ["نوع المؤسسة", "Organization type"],
  phone: ["الهاتف", "Phone"],
  studentsCount: ["مجموع الطلاب", "Students"],
  status: ["الحالة", "Status"],
  actions: ["الإجراءات", "Actions"],
  active: ["فعالة", "Active"],
  inactive: ["غير فعالة", "Inactive"],
  loading: ["جارٍ التحميل...", "Loading..."],
  noOrganizations: ["لا توجد مؤسسات", "No organizations found"],
  slug: ["المعرّف المختصر", "Slug"],
  adminPassword: [
    "كلمة مرور مدير المؤسسة",
    "Organization admin password",
  ],
  address: ["العنوان", "Address"],
  logo: ["شعار المؤسسة", "Organization logo"],
  chooseImage: ["اضغط لاختيار صورة من الجهاز", "Choose an image from device"],
  imageHint: [
    "PNG أو JPG أو WebP، بحد أقصى 5 ميغابايت",
    "PNG, JPG or WebP, up to 5 MB",
  ],
  removeLogo: ["إزالة الشعار", "Remove logo"],
  save: ["حفظ", "Save"],
  saving: ["جارٍ الحفظ...", "Saving..."],
  cancel: ["إلغاء", "Cancel"],
  edit: ["تعديل", "Edit"],
  delete: ["حذف", "Delete"],
  deleting: ["جارٍ الحذف...", "Deleting..."],
  confirm: ["تأكيد", "Confirm"],
  processing: ["جارٍ التنفيذ...", "Processing..."],
  subscriptionsSubtitle: [
    "إدارة الخطط ودورات الاشتراك لكل مؤسسة",
    "Manage plans and subscription lifecycles",
  ],
  addSubscription: ["إضافة اشتراك", "Add subscription"],
  editSubscription: ["تعديل الاشتراك", "Edit subscription"],
  extendSubscription: ["تمديد الاشتراك", "Extend subscription"],
  searchSubscriptions: [
    "ابحث باسم المؤسسة أو الخطة",
    "Search by organization or plan",
  ],
  organization: ["المؤسسة", "Organization"],
  chooseOrganization: ["اختر المؤسسة", "Select organization"],
  plan: ["الخطة", "Plan"],
  price: ["السعر", "Price"],
  startDate: ["تاريخ البدء", "Start date"],
  endDate: ["تاريخ الانتهاء", "End date"],
  newEndDate: ["تاريخ الانتهاء الجديد", "New end date"],
  extending: ["جارٍ التمديد...", "Extending..."],
  activeStatus: ["نشط", "Active"],
  expiredStatus: ["منتهي", "Expired"],
  pausedStatus: ["متوقف", "Paused"],
  noSubscriptions: ["لا توجد اشتراكات", "No subscriptions found"],
  activate: ["تنشيط", "Activate"],
  pause: ["إيقاف", "Pause"],
  activateSubscription: ["تنشيط الاشتراك", "Activate subscription"],
  pauseSubscription: ["إيقاف الاشتراك", "Pause subscription"],
  deleteSubscription: ["حذف الاشتراك", "Delete subscription"],
  activatePrompt: [
    "هل تريد إعادة تنشيط هذا الاشتراك؟",
    "Do you want to reactivate this subscription?",
  ],
  pausePrompt: [
    "هل تريد إيقاف هذا الاشتراك مؤقتًا؟",
    "Do you want to pause this subscription?",
  ],
  deleteSubscriptionPrompt: [
    "هل تريد حذف هذا الاشتراك؟ لا يمكن التراجع عن هذا الإجراء.",
    "Delete this subscription? This action cannot be undone.",
  ],
  backToOrganizations: ["العودة إلى المؤسسات", "Back to organizations"],
  users: ["المستخدمون", "Users"],
  students: ["الطلاب", "Students"],
  teachers: ["المعلمون", "Teachers"],
  subscriptionHistory: ["سجل الاشتراكات", "Subscription history"],
  noSubscriptionHistory: [
    "لا يوجد سجل اشتراكات",
    "No subscription history",
  ],
  close: ["إغلاق", "Close"],
  unexpectedError: ["حدث خطأ غير متوقع", "An unexpected error occurred"],
  previous: ["السابق", "Previous"],
  next: ["التالي", "Next"],
  invalidOrganization: [
    "رقم المؤسسة غير صالح",
    "Invalid organization identifier",
  ],
  school: ["مدرسة", "School"],
  institute: ["معهد", "Institute"],
} as const;

export type PlatformCopyKey = keyof typeof copy;

export function usePlatformCopy() {
  const locale = useLocale();
  const c = (key: PlatformCopyKey): string =>
    copy[key][locale.isArabic ? 0 : 1];

  return { ...locale, c };
}
